name: Publish KB Mirror

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *"   # nightly; optional

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tiktoken html2text tenacity mkdocs mkdocs-material

      - name: Export from Zendesk
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        run: |
          python export_zendesk_helpcenter.py

      - name: Build Markdown
        run: python mkdocs_build.py

      - name: Build static site
        run: mkdocs build

      - name: Upload export JSON
        uses: actions/upload-artifact@v4
        with:
          name: zendesk_export
          path: zendesk_export/


      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
